name: Fetch TEMPO NO2 .nc file

on:
  schedule:
    - cron: '0 * * * *'   # 每小時整點 (UTC)
  workflow_dispatch:

concurrency:
  group: fetch-tempo
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      OUTPUT_DIR: public/tempo
      SCRIPT: scripts/fetch_tempo_no2.py

    steps:
      # 1) 取出 main 分支（工作目錄 = repo root）
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 1

      # 方便除錯：看一下目前在哪裡、有哪些檔案
      - name: Debug - show workspace before run
        run: |
          echo "PWD = $PWD"
          git rev-parse --abbrev-ref HEAD
          ls -la
          ls -la scripts || true
      # 2) 系統層的 GDAL
      - name: Install GDAL
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev
      # 3) Python 3.11 + 套件
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          python -c "import rasterio, sys; print('rasterio OK:', rasterio.__version__)"
      # 4) 執行抓取＋產生 tiles（輸出到 ${OUTPUT_DIR}）
      - name: Run fetch script
        env:
          EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
          EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
        run: |
          mkdir -p "${OUTPUT_DIR}"
          python "${SCRIPT}"
          echo "---- List OUTPUT ----"
          ls -R "${OUTPUT_DIR}" || true
          pwd
      # 5) 第二次 checkout：把 gh-pages 取到子資料夾 gh-pages/
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0   # 建議留歷史

      # 6) 複製 main 產出的檔案 → gh-pages/tempo/
      - name: Copy assets into gh-pages
        run: |
          mkdir -p gh-pages/tempo
          ls -R public
          rsync -av ../public/tempo/tiles /home/runner/work/Aircast/Aircast/gh-pages/tempo/
          echo "---- List gh-pages/tempo ----"
          ls -R gh-pages/tempo || true
      # 7) 提交 & 推送 gh-pages
      - name: Commit & push to gh-pages
        working-directory: gh-pages
        run: |
          git config user.name "aircast-bot"
          git config user.email "actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: refresh TEMPO assets" || echo "No changes"
          git push origin gh-pages
